### ISSUE TITLE
Make this repo (and other CSCI 3155 repos) private?

### ISSUE THREAD

**Issue by bechang** [taylorjandrews/CSCI-3155-Lab4#1]
Dear Taylor,

The development effort in the lab projects is significant. So that future 3155 students can get as much out of the lab projects, could you convert this repo (and other CSCI 3155 repos) into a private one or otherwise take down these publicly available repositories?

Thank you for your consideration.

Sincerely,
Bor-Yuh Evan Chang

**Comment by taylorjandrews** [comment]
Hello,

I will immediately take down the repositories.

Best Regards,
Taylor Andrews
